name = "tsundoc"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tsundoc-db"
database_id = "70c753b9-7864-4d3e-96c4-3e562d9947e3"
migrations_dir = "src/db/migrations"

[env.staging]
name = "tsundoc-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "tsundoc-db-staging"
database_id = "89554ffe-ae60-443e-a441-105d011116c7"
migrations_dir = "src/db/migrations"
